// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package com.app.protobuffers;

public final class OrderBuffer {
  private OrderBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string album_name = 1;
    /**
     * <code>required string album_name = 1;</code>
     */
    boolean hasAlbumName();
    /**
     * <code>required string album_name = 1;</code>
     */
    java.lang.String getAlbumName();
    /**
     * <code>required string album_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getAlbumNameBytes();

    // required string artist = 2;
    /**
     * <code>required string artist = 2;</code>
     */
    boolean hasArtist();
    /**
     * <code>required string artist = 2;</code>
     */
    java.lang.String getArtist();
    /**
     * <code>required string artist = 2;</code>
     */
    com.google.protobuf.ByteString
        getArtistBytes();

    // required string username = 3;
    /**
     * <code>required string username = 3;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 3;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 3;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 4;
    /**
     * <code>required string password = 4;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // optional string archivePath = 5;
    /**
     * <code>optional string archivePath = 5;</code>
     */
    boolean hasArchivePath();
    /**
     * <code>optional string archivePath = 5;</code>
     */
    java.lang.String getArchivePath();
    /**
     * <code>optional string archivePath = 5;</code>
     */
    com.google.protobuf.ByteString
        getArchivePathBytes();

    // optional .protobuffers.Order.Job job = 6 [default = NOTDONE];
    /**
     * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
     */
    boolean hasJob();
    /**
     * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
     */
    com.app.protobuffers.OrderBuffer.Order.Job getJob();

    // optional .protobuffers.Order.AlbumType type = 7 [default = FREE];
    /**
     * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
     */
    boolean hasType();
    /**
     * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
     */
    com.app.protobuffers.OrderBuffer.Order.AlbumType getType();

    // optional int32 credit = 8 [default = 0];
    /**
     * <code>optional int32 credit = 8 [default = 0];</code>
     */
    boolean hasCredit();
    /**
     * <code>optional int32 credit = 8 [default = 0];</code>
     */
    int getCredit();
  }
  /**
   * Protobuf type {@code protobuffers.Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage
      implements OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Order(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Order defaultInstance;
    public static Order getDefaultInstance() {
      return defaultInstance;
    }

    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              albumName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              artist_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              username_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              password_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              archivePath_ = input.readBytes();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.app.protobuffers.OrderBuffer.Order.Job value = com.app.protobuffers.OrderBuffer.Order.Job.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                job_ = value;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.app.protobuffers.OrderBuffer.Order.AlbumType value = com.app.protobuffers.OrderBuffer.Order.AlbumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                type_ = value;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              credit_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.protobuffers.OrderBuffer.internal_static_protobuffers_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.protobuffers.OrderBuffer.internal_static_protobuffers_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.protobuffers.OrderBuffer.Order.class, com.app.protobuffers.OrderBuffer.Order.Builder.class);
    }

    public static com.google.protobuf.Parser<Order> PARSER =
        new com.google.protobuf.AbstractParser<Order>() {
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protobuffers.Order.AlbumType}
     */
    public enum AlbumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FREE = 0;</code>
       */
      FREE(0, 0),
      /**
       * <code>NONFREE = 1;</code>
       */
      NONFREE(1, 1),
      /**
       * <code>PROMO = 2;</code>
       */
      PROMO(2, 2),
      ;

      /**
       * <code>FREE = 0;</code>
       */
      public static final int FREE_VALUE = 0;
      /**
       * <code>NONFREE = 1;</code>
       */
      public static final int NONFREE_VALUE = 1;
      /**
       * <code>PROMO = 2;</code>
       */
      public static final int PROMO_VALUE = 2;


      public final int getNumber() { return value; }

      public static AlbumType valueOf(int value) {
        switch (value) {
          case 0: return FREE;
          case 1: return NONFREE;
          case 2: return PROMO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AlbumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AlbumType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AlbumType>() {
              public AlbumType findValueByNumber(int number) {
                return AlbumType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.app.protobuffers.OrderBuffer.Order.getDescriptor().getEnumTypes().get(0);
      }

      private static final AlbumType[] VALUES = values();

      public static AlbumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private AlbumType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuffers.Order.AlbumType)
    }

    /**
     * Protobuf enum {@code protobuffers.Order.Job}
     */
    public enum Job
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DONE = 0;</code>
       */
      DONE(0, 0),
      /**
       * <code>NOTDONE = 1;</code>
       */
      NOTDONE(1, 1),
      /**
       * <code>FAILED = 2;</code>
       */
      FAILED(2, 2),
      ;

      /**
       * <code>DONE = 0;</code>
       */
      public static final int DONE_VALUE = 0;
      /**
       * <code>NOTDONE = 1;</code>
       */
      public static final int NOTDONE_VALUE = 1;
      /**
       * <code>FAILED = 2;</code>
       */
      public static final int FAILED_VALUE = 2;


      public final int getNumber() { return value; }

      public static Job valueOf(int value) {
        switch (value) {
          case 0: return DONE;
          case 1: return NOTDONE;
          case 2: return FAILED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Job>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Job>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Job>() {
              public Job findValueByNumber(int number) {
                return Job.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.app.protobuffers.OrderBuffer.Order.getDescriptor().getEnumTypes().get(1);
      }

      private static final Job[] VALUES = values();

      public static Job valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Job(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuffers.Order.Job)
    }

    private int bitField0_;
    // required string album_name = 1;
    public static final int ALBUM_NAME_FIELD_NUMBER = 1;
    private java.lang.Object albumName_;
    /**
     * <code>required string album_name = 1;</code>
     */
    public boolean hasAlbumName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string album_name = 1;</code>
     */
    public java.lang.String getAlbumName() {
      java.lang.Object ref = albumName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          albumName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string album_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumNameBytes() {
      java.lang.Object ref = albumName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string artist = 2;
    public static final int ARTIST_FIELD_NUMBER = 2;
    private java.lang.Object artist_;
    /**
     * <code>required string artist = 2;</code>
     */
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string artist = 2;</code>
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          artist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string artist = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string username = 3;
    public static final int USERNAME_FIELD_NUMBER = 3;
    private java.lang.Object username_;
    /**
     * <code>required string username = 3;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string username = 3;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 4;
    public static final int PASSWORD_FIELD_NUMBER = 4;
    private java.lang.Object password_;
    /**
     * <code>required string password = 4;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string archivePath = 5;
    public static final int ARCHIVEPATH_FIELD_NUMBER = 5;
    private java.lang.Object archivePath_;
    /**
     * <code>optional string archivePath = 5;</code>
     */
    public boolean hasArchivePath() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string archivePath = 5;</code>
     */
    public java.lang.String getArchivePath() {
      java.lang.Object ref = archivePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          archivePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string archivePath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getArchivePathBytes() {
      java.lang.Object ref = archivePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        archivePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .protobuffers.Order.Job job = 6 [default = NOTDONE];
    public static final int JOB_FIELD_NUMBER = 6;
    private com.app.protobuffers.OrderBuffer.Order.Job job_;
    /**
     * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
     */
    public boolean hasJob() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
     */
    public com.app.protobuffers.OrderBuffer.Order.Job getJob() {
      return job_;
    }

    // optional .protobuffers.Order.AlbumType type = 7 [default = FREE];
    public static final int TYPE_FIELD_NUMBER = 7;
    private com.app.protobuffers.OrderBuffer.Order.AlbumType type_;
    /**
     * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
     */
    public com.app.protobuffers.OrderBuffer.Order.AlbumType getType() {
      return type_;
    }

    // optional int32 credit = 8 [default = 0];
    public static final int CREDIT_FIELD_NUMBER = 8;
    private int credit_;
    /**
     * <code>optional int32 credit = 8 [default = 0];</code>
     */
    public boolean hasCredit() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 credit = 8 [default = 0];</code>
     */
    public int getCredit() {
      return credit_;
    }

    private void initFields() {
      albumName_ = "";
      artist_ = "";
      username_ = "";
      password_ = "";
      archivePath_ = "";
      job_ = com.app.protobuffers.OrderBuffer.Order.Job.NOTDONE;
      type_ = com.app.protobuffers.OrderBuffer.Order.AlbumType.FREE;
      credit_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAlbumName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArtist()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAlbumNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getArtistBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getArchivePathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, job_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, type_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, credit_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAlbumNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getArtistBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getArchivePathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, job_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, type_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, credit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.protobuffers.OrderBuffer.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.protobuffers.OrderBuffer.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuffers.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.app.protobuffers.OrderBuffer.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.protobuffers.OrderBuffer.internal_static_protobuffers_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.protobuffers.OrderBuffer.internal_static_protobuffers_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.protobuffers.OrderBuffer.Order.class, com.app.protobuffers.OrderBuffer.Order.Builder.class);
      }

      // Construct using com.app.protobuffers.OrderBuffer.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        albumName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        artist_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        archivePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        job_ = com.app.protobuffers.OrderBuffer.Order.Job.NOTDONE;
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = com.app.protobuffers.OrderBuffer.Order.AlbumType.FREE;
        bitField0_ = (bitField0_ & ~0x00000040);
        credit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.protobuffers.OrderBuffer.internal_static_protobuffers_Order_descriptor;
      }

      public com.app.protobuffers.OrderBuffer.Order getDefaultInstanceForType() {
        return com.app.protobuffers.OrderBuffer.Order.getDefaultInstance();
      }

      public com.app.protobuffers.OrderBuffer.Order build() {
        com.app.protobuffers.OrderBuffer.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.protobuffers.OrderBuffer.Order buildPartial() {
        com.app.protobuffers.OrderBuffer.Order result = new com.app.protobuffers.OrderBuffer.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.albumName_ = albumName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.artist_ = artist_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.archivePath_ = archivePath_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.job_ = job_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.credit_ = credit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.protobuffers.OrderBuffer.Order) {
          return mergeFrom((com.app.protobuffers.OrderBuffer.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.protobuffers.OrderBuffer.Order other) {
        if (other == com.app.protobuffers.OrderBuffer.Order.getDefaultInstance()) return this;
        if (other.hasAlbumName()) {
          bitField0_ |= 0x00000001;
          albumName_ = other.albumName_;
          onChanged();
        }
        if (other.hasArtist()) {
          bitField0_ |= 0x00000002;
          artist_ = other.artist_;
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000004;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000008;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasArchivePath()) {
          bitField0_ |= 0x00000010;
          archivePath_ = other.archivePath_;
          onChanged();
        }
        if (other.hasJob()) {
          setJob(other.getJob());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCredit()) {
          setCredit(other.getCredit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAlbumName()) {
          
          return false;
        }
        if (!hasArtist()) {
          
          return false;
        }
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.protobuffers.OrderBuffer.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.protobuffers.OrderBuffer.Order) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string album_name = 1;
      private java.lang.Object albumName_ = "";
      /**
       * <code>required string album_name = 1;</code>
       */
      public boolean hasAlbumName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string album_name = 1;</code>
       */
      public java.lang.String getAlbumName() {
        java.lang.Object ref = albumName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          albumName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string album_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumNameBytes() {
        java.lang.Object ref = albumName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string album_name = 1;</code>
       */
      public Builder setAlbumName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        albumName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string album_name = 1;</code>
       */
      public Builder clearAlbumName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        albumName_ = getDefaultInstance().getAlbumName();
        onChanged();
        return this;
      }
      /**
       * <code>required string album_name = 1;</code>
       */
      public Builder setAlbumNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        albumName_ = value;
        onChanged();
        return this;
      }

      // required string artist = 2;
      private java.lang.Object artist_ = "";
      /**
       * <code>required string artist = 2;</code>
       */
      public boolean hasArtist() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string artist = 2;</code>
       */
      public java.lang.String getArtist() {
        java.lang.Object ref = artist_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          artist_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string artist = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArtistBytes() {
        java.lang.Object ref = artist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string artist = 2;</code>
       */
      public Builder setArtist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string artist = 2;</code>
       */
      public Builder clearArtist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        artist_ = getDefaultInstance().getArtist();
        onChanged();
        return this;
      }
      /**
       * <code>required string artist = 2;</code>
       */
      public Builder setArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }

      // required string username = 3;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 3;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string username = 3;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 3;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 3;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 3;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 4;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 4;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 4;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        password_ = value;
        onChanged();
        return this;
      }

      // optional string archivePath = 5;
      private java.lang.Object archivePath_ = "";
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public boolean hasArchivePath() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public java.lang.String getArchivePath() {
        java.lang.Object ref = archivePath_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          archivePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public com.google.protobuf.ByteString
          getArchivePathBytes() {
        java.lang.Object ref = archivePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          archivePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public Builder setArchivePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        archivePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public Builder clearArchivePath() {
        bitField0_ = (bitField0_ & ~0x00000010);
        archivePath_ = getDefaultInstance().getArchivePath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string archivePath = 5;</code>
       */
      public Builder setArchivePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        archivePath_ = value;
        onChanged();
        return this;
      }

      // optional .protobuffers.Order.Job job = 6 [default = NOTDONE];
      private com.app.protobuffers.OrderBuffer.Order.Job job_ = com.app.protobuffers.OrderBuffer.Order.Job.NOTDONE;
      /**
       * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
       */
      public boolean hasJob() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
       */
      public com.app.protobuffers.OrderBuffer.Order.Job getJob() {
        return job_;
      }
      /**
       * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
       */
      public Builder setJob(com.app.protobuffers.OrderBuffer.Order.Job value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        job_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuffers.Order.Job job = 6 [default = NOTDONE];</code>
       */
      public Builder clearJob() {
        bitField0_ = (bitField0_ & ~0x00000020);
        job_ = com.app.protobuffers.OrderBuffer.Order.Job.NOTDONE;
        onChanged();
        return this;
      }

      // optional .protobuffers.Order.AlbumType type = 7 [default = FREE];
      private com.app.protobuffers.OrderBuffer.Order.AlbumType type_ = com.app.protobuffers.OrderBuffer.Order.AlbumType.FREE;
      /**
       * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
       */
      public com.app.protobuffers.OrderBuffer.Order.AlbumType getType() {
        return type_;
      }
      /**
       * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
       */
      public Builder setType(com.app.protobuffers.OrderBuffer.Order.AlbumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protobuffers.Order.AlbumType type = 7 [default = FREE];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = com.app.protobuffers.OrderBuffer.Order.AlbumType.FREE;
        onChanged();
        return this;
      }

      // optional int32 credit = 8 [default = 0];
      private int credit_ ;
      /**
       * <code>optional int32 credit = 8 [default = 0];</code>
       */
      public boolean hasCredit() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 credit = 8 [default = 0];</code>
       */
      public int getCredit() {
        return credit_;
      }
      /**
       * <code>optional int32 credit = 8 [default = 0];</code>
       */
      public Builder setCredit(int value) {
        bitField0_ |= 0x00000080;
        credit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 credit = 8 [default = 0];</code>
       */
      public Builder clearCredit() {
        bitField0_ = (bitField0_ & ~0x00000080);
        credit_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuffers.Order)
    }

    static {
      defaultInstance = new Order(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuffers.Order)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffers_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuffers_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Order.proto\022\014protobuffers\"\262\002\n\005Order\022\022\n" +
      "\nalbum_name\030\001 \002(\t\022\016\n\006artist\030\002 \002(\t\022\020\n\010use" +
      "rname\030\003 \002(\t\022\020\n\010password\030\004 \002(\t\022\023\n\013archive" +
      "Path\030\005 \001(\t\022-\n\003job\030\006 \001(\0162\027.protobuffers.O" +
      "rder.Job:\007NOTDONE\0221\n\004type\030\007 \001(\0162\035.protob" +
      "uffers.Order.AlbumType:\004FREE\022\021\n\006credit\030\010" +
      " \001(\005:\0010\"-\n\tAlbumType\022\010\n\004FREE\020\000\022\013\n\007NONFRE" +
      "E\020\001\022\t\n\005PROMO\020\002\"(\n\003Job\022\010\n\004DONE\020\000\022\013\n\007NOTDO" +
      "NE\020\001\022\n\n\006FAILED\020\002B#\n\024com.app.protobuffers" +
      "B\013OrderBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuffers_Order_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuffers_Order_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuffers_Order_descriptor,
              new java.lang.String[] { "AlbumName", "Artist", "Username", "Password", "ArchivePath", "Job", "Type", "Credit", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
